"""Stable runtime identifiers for material-flow capabilities."""

MATERIAL_FLOW_IDEMPOTENCY_NAMESPACE = "material-flow"
SORTER_INBOUND_RUNTIME_SOURCE = "MATERIAL_FLOW_SORTER_INBOUND"
RECONCILIATION_RUNTIME_SOURCE = "MATERIAL_FLOW_RECONCILIATION"

__all__ = [
    "MATERIAL_FLOW_IDEMPOTENCY_NAMESPACE",
    "RECONCILIATION_RUNTIME_SOURCE",
    "SORTER_INBOUND_RUNTIME_SOURCE",
]
