"""SMT 分拣入库插件 P0 合同常量。"""

SMT_SORTING_INBOUND_PLUGIN_KEY = "SMT_SORTING_INBOUND"
SMT_SORTING_INBOUND_CONTRACT_VERSION = "2026-06-01.p0"

SORTING_CONTEXT_SCHEMA_VERSION = 1

ROLE_SORTING_SOURCE_ARM = "SORTING_SOURCE_ARM"
ROLE_SORTING_TARGET_ARM = "SORTING_TARGET_ARM"
ROLE_SORTING_SCAN_PLATFORM = "SORTING_SCAN_PLATFORM"
ROLE_SORTING_WORKSTATION = "SORTING_WORKSTATION"

PHASE_WAITING_SOURCE_PICK = "WAITING_SOURCE_PICK"
PHASE_WAITING_SCAN = "WAITING_SCAN"
PHASE_WAITING_TARGET_PLACE = "WAITING_TARGET_PLACE"
PHASE_WAITING_TARGET_BIN_SWITCH = "WAITING_TARGET_BIN_SWITCH"
PHASE_WAITING_NG_PLACE = "WAITING_NG_PLACE"
PHASE_COMPLETED = "COMPLETED"

COMMAND_SOURCE_PICK = "SORTING_SOURCE_PICK"
COMMAND_TARGET_PLACE = "SORTING_TARGET_PLACE"
COMMAND_NG_PLACE = "SORTING_NG_PLACE"

EVENT_SOURCE_PICK_RESULT = "SORTING_SOURCE_PICK_RESULT"
EVENT_SOURCE_PICK_REQUESTED = "SORTING_SOURCE_PICK_REQUESTED"
EVENT_TARGET_PLACE_RESULT = "SORTING_TARGET_PLACE_RESULT"
EVENT_NG_PLACE_RESULT = "SORTING_NG_PLACE_RESULT"
EVENT_WORKING_BIN_SCAN = "WORKING_BIN_SCAN"
EVENT_SESSION_COMPLETE_REQUESTED = "SORTING_SESSION_COMPLETE_REQUESTED"

NG_REASON_LOCAL_SORTING_NG = "LOCAL_SORTING_NG"
NG_REASON_MATERIAL_CONFLICT = "NG_MATERIAL_CONFLICT"

__all__ = [
    "COMMAND_NG_PLACE",
    "COMMAND_SOURCE_PICK",
    "COMMAND_TARGET_PLACE",
    "EVENT_NG_PLACE_RESULT",
    "EVENT_SESSION_COMPLETE_REQUESTED",
    "EVENT_SOURCE_PICK_REQUESTED",
    "EVENT_SOURCE_PICK_RESULT",
    "EVENT_TARGET_PLACE_RESULT",
    "EVENT_WORKING_BIN_SCAN",
    "NG_REASON_LOCAL_SORTING_NG",
    "NG_REASON_MATERIAL_CONFLICT",
    "PHASE_COMPLETED",
    "PHASE_WAITING_NG_PLACE",
    "PHASE_WAITING_SCAN",
    "PHASE_WAITING_SOURCE_PICK",
    "PHASE_WAITING_TARGET_BIN_SWITCH",
    "PHASE_WAITING_TARGET_PLACE",
    "ROLE_SORTING_SCAN_PLATFORM",
    "ROLE_SORTING_SOURCE_ARM",
    "ROLE_SORTING_TARGET_ARM",
    "ROLE_SORTING_WORKSTATION",
    "SMT_SORTING_INBOUND_CONTRACT_VERSION",
    "SMT_SORTING_INBOUND_PLUGIN_KEY",
    "SORTING_CONTEXT_SCHEMA_VERSION",
]
