from src.app.runtime.system_capabilities.wms.query_definition import build_wms_query_capability_definition
from src.app.wms_integration.ports.reconciliation_operations import CHECK_FULL_DRIFT

DEFINITION = build_wms_query_capability_definition(CHECK_FULL_DRIFT)
