"""Api Application secret

Revision ID: 67a8b5fa1d60
Revises: cbc99c386c79
Create Date: 2026-01-30 14:07:53.919336+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67a8b5fa1d60"
down_revision: Union[str, Sequence[str], None] = "cbc99c386c79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS apptype CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS appstatus CASCADE")

    op.create_table("api_access_logs",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("app_id", sa.String(length=50), nullable=False),
    sa.Column("app_name", sa.String(length=100), nullable=False),
    sa.Column("request_id", sa.String(length=50), nullable=False),
    sa.Column("method", sa.String(length=10), nullable=False),
    sa.Column("path", sa.String(length=500), nullable=False),
    sa.Column("status_code", sa.Integer(), nullable=False),
    sa.Column("response_time_ms", sa.Integer(), nullable=False),
    sa.Column("ip_address", sa.String(length=50), nullable=False),
    sa.Column("user_agent", sa.String(length=500), nullable=True),
    sa.Column("error_message", sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index("ix_api_log_app_time", "api_access_logs", ["app_id", "created_at"], unique=False, schema="wes_sys")
    op.create_index("ix_api_log_path", "api_access_logs", ["path", "created_at"], unique=False, schema="wes_sys", postgresql_ops={"path": "text_pattern_ops"})
    op.create_index("ix_api_log_status", "api_access_logs", ["status_code", "created_at"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_api_access_logs_app_id"), "api_access_logs", ["app_id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_api_access_logs_id"), "api_access_logs", ["id"], unique=False, schema="wes_sys")
    op.create_table("api_applications",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("app_name", sa.String(length=100), nullable=False),
    sa.Column("app_type", sa.Enum("ECS", "RCS", "WMS", "ThirdParty", name="apptype"), nullable=False),
    sa.Column("description", sa.String(length=500), nullable=True),
    sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
    sa.Column("rate_limit_per_hour", sa.Integer(), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=True),
    sa.Column("app_id", sa.String(length=50), nullable=False),
    sa.Column("app_secret_encrypted", sa.String(length=500), nullable=False),
    sa.Column("status", sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="appstatus"), nullable=False),
    sa.Column("ip_whitelist", sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index("ix_api_app_status", "api_applications", ["status", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index("ix_api_app_type", "api_applications", ["app_type", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_api_applications_app_id"), "api_applications", ["app_id"], unique=True, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_api_applications_id"), "api_applications", ["id"], unique=False, schema="wes_sys")
    op.create_table("api_app_permissions",
    sa.Column("app_id", sa.Integer(), nullable=False),
    sa.Column("permission_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["app_id"], ["wes_sys.api_applications.id"], name=op.f("fk_api_app_permissions_app_id_api_applications"), ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["permission_id"], ["wes_sys.permissions.id"], name=op.f("fk_api_app_permissions_permission_id_permissions"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("app_id", "permission_id", name=op.f("pk_api_app_permissions")),
    schema="wes_sys"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_app_permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_api_applications_id"), table_name="api_applications", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_api_applications_app_id"), table_name="api_applications", schema="wes_sys")
    op.drop_index("ix_api_app_type", table_name="api_applications", schema="wes_sys")
    op.drop_index("ix_api_app_status", table_name="api_applications", schema="wes_sys")
    op.drop_table("api_applications", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_api_access_logs_id"), table_name="api_access_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_api_access_logs_app_id"), table_name="api_access_logs", schema="wes_sys")
    op.drop_index("ix_api_log_status", table_name="api_access_logs", schema="wes_sys")
    op.drop_index("ix_api_log_path", table_name="api_access_logs", schema="wes_sys", postgresql_ops={"path": "text_pattern_ops"})
    op.drop_index("ix_api_log_app_time", table_name="api_access_logs", schema="wes_sys")
    op.drop_table("api_access_logs", schema="wes_sys")
    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS appstatus CASCADE")
        # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS apptype CASCADE")
        # ### end Alembic commands ###
