"""Initial_migration

Revision ID: cbc99c386c79
Revises: 
Create Date: 2026-01-29 19:28:06.024464+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbc99c386c79"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS operastatus CASCADE")

    op.create_table("demo_products",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("name", sa.String(length=100), nullable=False, comment="产品名称"),
    sa.Column("price", sa.Float(), nullable=False),
    sa.Column("stock", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index("demo_products_name_active_unique", "demo_products", ["name"], unique=True, schema="wes_biz", postgresql_where="NOT is_deleted")
    op.create_index(op.f("ix_wes_biz_demo_products_id"), "demo_products", ["id"], unique=False, schema="wes_biz")
    op.create_table("audit_logs",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("trace_id", sa.String(length=64), nullable=False),
    sa.Column("username", sa.String(length=32), nullable=True),
    sa.Column("method", sa.String(length=10), nullable=False),
    sa.Column("title", sa.String(length=100), nullable=False),
    sa.Column("path", sa.String(length=200), nullable=False),
    sa.Column("ip", sa.String(length=64), nullable=False),
    sa.Column("country", sa.String(length=64), nullable=True),
    sa.Column("region", sa.String(length=64), nullable=True),
    sa.Column("city", sa.String(length=64), nullable=True),
    sa.Column("user_agent", sa.String(length=500), nullable=False),
    sa.Column("os", sa.String(length=64), nullable=True),
    sa.Column("browser", sa.String(length=64), nullable=True),
    sa.Column("device", sa.String(length=64), nullable=True),
    sa.Column("args", sa.JSON(), nullable=True),
    sa.Column("status", sa.Enum("FAIL", "SUCCESS", name="operastatus"), nullable=False),
    sa.Column("code", sa.String(length=20), nullable=False),
    sa.Column("msg", sa.Text(), nullable=True),
    sa.Column("cost_time", sa.Float(), nullable=False),
    sa.Column("opera_time", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_audit_logs_id"), "audit_logs", ["id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_audit_logs_opera_time"), "audit_logs", ["opera_time"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_audit_logs_trace_id"), "audit_logs", ["trace_id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_audit_logs_username"), "audit_logs", ["username"], unique=False, schema="wes_sys")
    op.create_table("permissions",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("parent_id", sa.Integer(), nullable=True),
    sa.Column("tree_path", sa.String(), nullable=False, comment="节点路径"),
    sa.Column("level", sa.Integer(), nullable=False, comment="节点层级"),
    sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序号"),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.Column("type", sa.String(), nullable=False),
    sa.Column("category", sa.String(length=50), nullable=True),
    sa.Column("resource", sa.String(length=50), nullable=True),
    sa.Column("action", sa.String(length=50), nullable=True),
    sa.Column("method", sa.String(length=10), nullable=True),
    sa.Column("path", sa.String(length=255), nullable=True),
    sa.Column("component", sa.String(length=255), nullable=True),
    sa.Column("icon", sa.String(length=50), nullable=True),
    sa.Column("redirect", sa.String(length=255), nullable=True),
    sa.Column("title", sa.String(length=100), nullable=True),
    sa.Column("is_hidden", sa.Boolean(), nullable=False),
    sa.Column("is_cached", sa.Boolean(), nullable=False),
    sa.Column("is_affix", sa.Boolean(), nullable=False),
    sa.Column("is_external", sa.Boolean(), nullable=False),
    sa.Column("external_url", sa.String(length=500), nullable=True),
    sa.Column("meta", sa.JSON(), nullable=True),
    sa.Column("api_permissions", sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(["parent_id"], ["wes_sys.permissions.id"], ),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index("ix_perm_api_deleted", "permissions", ["method", "path", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index("ix_perm_menu_deleted", "permissions", ["type", "is_hidden", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index("ix_perm_parent_sort_deleted", "permissions", ["parent_id", "sort_order", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index("ix_perm_type_deleted", "permissions", ["type", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_id"), "permissions", ["id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_parent_id"), "permissions", ["parent_id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_tree_path"), "permissions", ["tree_path"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_type"), "permissions", ["type"], unique=False, schema="wes_sys")
    op.create_index("ux_perm_name_deleted", "permissions", ["name"], unique=True, schema="wes_sys", postgresql_where="NOT is_deleted")
    op.create_table("roles",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_roles_id"), "roles", ["id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_roles_name"), "roles", ["name"], unique=False, schema="wes_sys")
    op.create_index("ux_roles_name_deleted", "roles", ["name"], unique=True, schema="wes_sys", postgresql_where="NOT is_deleted")
    op.create_table("users",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("username", sa.String(length=50), nullable=False),
    sa.Column("email", sa.String(length=100), nullable=False),
    sa.Column("full_name", sa.String(length=100), nullable=True),
    sa.Column("hashed_password", sa.String(length=255), nullable=False),
    sa.Column("is_superuser", sa.Boolean(), nullable=False),
    sa.Column("is_multi_login", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_users_email"), "users", ["email"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_users_id"), "users", ["id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_users_username"), "users", ["username"], unique=False, schema="wes_sys")
    op.create_table("demo_product_lists",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("product_id", sa.BigInteger(), nullable=True),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["product_id"], ["wes_biz.demo_products.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_demo_product_lists_id"), "demo_product_lists", ["id"], unique=False, schema="wes_biz")
    op.create_table("role_permissions",
    sa.Column("role_id", sa.BigInteger(), nullable=False),
    sa.Column("permission_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["permission_id"], ["wes_sys.permissions.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["role_id"], ["wes_sys.roles.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("role_id", "permission_id"),
    schema="wes_sys",
    comment="角色-权限关联表"
    )
    op.create_table("user_roles",
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.Column("role_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["role_id"], ["wes_sys.roles.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["wes_sys.users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("user_id", "role_id"),
    schema="wes_sys",
    comment="用户-角色关联表"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles", schema="wes_sys")
    op.drop_table("role_permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_biz_demo_product_lists_id"), table_name="demo_product_lists", schema="wes_biz")
    op.drop_table("demo_product_lists", schema="wes_biz")
    op.drop_index(op.f("ix_wes_sys_users_username"), table_name="users", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_users_id"), table_name="users", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_users_email"), table_name="users", schema="wes_sys")
    op.drop_table("users", schema="wes_sys")
    op.drop_index("ux_roles_name_deleted", table_name="roles", schema="wes_sys", postgresql_where="NOT is_deleted")
    op.drop_index(op.f("ix_wes_sys_roles_name"), table_name="roles", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_roles_id"), table_name="roles", schema="wes_sys")
    op.drop_table("roles", schema="wes_sys")
    op.drop_index("ux_perm_name_deleted", table_name="permissions", schema="wes_sys", postgresql_where="NOT is_deleted")
    op.drop_index(op.f("ix_wes_sys_permissions_type"), table_name="permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_permissions_tree_path"), table_name="permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_permissions_parent_id"), table_name="permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_permissions_id"), table_name="permissions", schema="wes_sys")
    op.drop_index("ix_perm_type_deleted", table_name="permissions", schema="wes_sys")
    op.drop_index("ix_perm_parent_sort_deleted", table_name="permissions", schema="wes_sys")
    op.drop_index("ix_perm_menu_deleted", table_name="permissions", schema="wes_sys")
    op.drop_index("ix_perm_api_deleted", table_name="permissions", schema="wes_sys")
    op.drop_table("permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_username"), table_name="audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_trace_id"), table_name="audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_opera_time"), table_name="audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_id"), table_name="audit_logs", schema="wes_sys")
    op.drop_table("audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_biz_demo_products_id"), table_name="demo_products", schema="wes_biz")
    op.drop_index("demo_products_name_active_unique", table_name="demo_products", schema="wes_biz", postgresql_where="NOT is_deleted")
    op.drop_table("demo_products", schema="wes_biz")
    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS operastatus CASCADE")
        # ### end Alembic commands ###
