"""create_workline_and_device_tables

Revision ID: 3db05fc3930f
Revises: 7530da1be3cd
Create Date: 2026-03-02 20:18:42.571616+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3db05fc3930f"
down_revision: Union[str, Sequence[str], None] = "7530da1be3cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("work_lines",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("line_code", sa.String(length=50), nullable=False),
    sa.Column("line_name", sa.String(length=100), nullable=False),
    sa.Column("line_type", sa.String(length=50), nullable=False),
    sa.Column("zone_name", sa.String(length=100), nullable=True),
    sa.Column("description", sa.String(length=500), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("capacity", sa.Integer(), nullable=True),
    sa.Column("sort_order", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_work_lines_id"), "work_lines", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_work_lines_line_code"), "work_lines", ["line_code"], unique=False, schema="wes_biz")
    op.create_table("devices",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("device_code", sa.String(length=50), nullable=False),
    sa.Column("device_name", sa.String(length=100), nullable=False),
    sa.Column("device_type", sa.String(length=50), nullable=False),
    sa.Column("work_line_id", sa.Integer(), nullable=True),
    sa.Column("description", sa.String(length=500), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("sort_order", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["work_line_id"], ["wes_biz.work_lines.id"], ),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_devices_device_code"), "devices", ["device_code"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_devices_id"), "devices", ["id"], unique=True, schema="wes_biz")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wes_biz_devices_id"), table_name="devices", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_devices_device_code"), table_name="devices", schema="wes_biz")
    op.drop_table("devices", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_work_lines_line_code"), table_name="work_lines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_work_lines_id"), table_name="work_lines", schema="wes_biz")
    op.drop_table("work_lines", schema="wes_biz")
    # ### end Alembic commands ###
