"""add parent sort index to menus

Revision ID: 6f84ab2bf6e6
Revises: 5d26a11a4cd9
Create Date: 2026-03-31 16:07:13.683842+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f84ab2bf6e6"
down_revision: Union[str, Sequence[str], None] = "5d26a11a4cd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(*, schema: str, table_name: str, index_name: str) -> bool:
    """Handle drifted databases where the legacy index may already be absent."""
    inspector = sa.inspect(op.get_bind())
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name, schema=schema))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("menus", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    if _index_exists(schema="wes_sys", table_name="menus", index_name=op.f("idx_tree_parent_sort")):
        op.drop_index(op.f("idx_tree_parent_sort"), table_name="menus", schema="wes_sys")
    if not _index_exists(schema="wes_sys", table_name="menus", index_name="idx_menus_parent_sort"):
        op.create_index("idx_menus_parent_sort", "menus", ["parent_id", "sort_order"], unique=False, schema="wes_sys")
    op.alter_column("permissions", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("permissions", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("false"),
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    if _index_exists(schema="wes_sys", table_name="menus", index_name="idx_menus_parent_sort"):
        op.drop_index("idx_menus_parent_sort", table_name="menus", schema="wes_sys")
    if not _index_exists(schema="wes_sys", table_name="menus", index_name=op.f("idx_tree_parent_sort")):
        op.create_index(op.f("idx_tree_parent_sort"), "menus", ["parent_id", "sort_order"], unique=False, schema="wes_sys")
    op.alter_column("menus", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("false"),
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    # ### end Alembic commands ###
