"""create workline session timeline inbox and outbox tables

Revision ID: 8f8180e751c3
Revises: e86574a11839
Create Date: 2026-03-17 09:30:47.214546+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f8180e751c3"
down_revision: Union[str, Sequence[str], None] = "e86574a11839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.dispatchtype CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.inboxkind CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.inboxstatus CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.outboxstatus CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.runmode CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.sessionstatus CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.sourcesystem CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.targettype CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.timelineactiontype CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.timelineactortype CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.timelinestage CASCADE")

    # 删除已存在的 ENUM 类型（如果存在）
    op.execute("DROP TYPE IF EXISTS wes_biz.timelinestatus CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("workline_sessions",
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("session_code", sa.String(length=100), nullable=False),
    sa.Column("workline_id", sa.Integer(), nullable=False),
    sa.Column("plugin_key", sa.String(length=100), nullable=False),
    sa.Column("business_key", sa.String(length=100), nullable=True),
    sa.Column("barcode", sa.String(length=100), nullable=True),
    sa.Column("context_json", sa.JSON(), nullable=True),
    sa.Column("context_schema_version", sa.String(length=50), nullable=True),
    sa.Column("started_at", sa.DateTime(), nullable=True),
    sa.Column("ended_at", sa.DateTime(), nullable=True),
    sa.Column("correlation_id", sa.String(length=100), nullable=True),
    sa.Column("current_wait_type", sa.String(length=100), nullable=True),
    sa.Column("current_wait_token", sa.String(length=200), nullable=True),
    sa.Column("waiting_since", sa.DateTime(), nullable=True),
    sa.Column("deadline_at", sa.DateTime(), nullable=True),
    sa.Column("awaiting_command_id", sa.Integer(), nullable=True),
    sa.Column("failure_domain", sa.String(length=100), nullable=True),
    sa.Column("failure_code", sa.String(length=50), nullable=True),
    sa.Column("failure_message", sa.Text(), nullable=True),
    sa.Column("retry_count", sa.Integer(), nullable=False),
    sa.Column("last_inbox_id", sa.Integer(), nullable=True),
    sa.Column("last_decision_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["awaiting_command_id"], ["wes_biz.device_commands.id"], ),
    sa.ForeignKeyConstraint(["workline_id"], ["wes_biz.work_lines.id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.Column("run_mode", sa.Enum("AUTO", "MANUAL", "SIMULATION", "REPLAY", name="runmode", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("status", sa.Enum("NEW", "RUNNING", "WAITING_DEVICE_RESULT", "WAITING_EXTERNAL", "MANUAL_HOLD", "COMPLETED", "FAILED", "CANCELLED", name="sessionstatus", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_workline_sessions_awaiting_command_id"), "workline_sessions", ["awaiting_command_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_barcode"), "workline_sessions", ["barcode"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_business_key"), "workline_sessions", ["business_key"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_correlation_id"), "workline_sessions", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_id"), "workline_sessions", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_plugin_key"), "workline_sessions", ["plugin_key"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_session_code"), "workline_sessions", ["session_code"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_started_at"), "workline_sessions", ["started_at"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_status"), "workline_sessions", ["status"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_sessions_workline_id"), "workline_sessions", ["workline_id"], unique=False, schema="wes_biz")
    op.create_table("workline_inbox",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("idempotency_key", sa.String(length=200), nullable=True),
    sa.Column("source_message_id", sa.String(length=200), nullable=True),
    sa.Column("workline_id", sa.Integer(), nullable=True),
    sa.Column("device_id", sa.Integer(), nullable=True),
    sa.Column("command_id", sa.Integer(), nullable=True),
    sa.Column("session_id", sa.Integer(), nullable=True),
    sa.Column("correlation_id", sa.String(length=100), nullable=True),
    sa.Column("payload_json", sa.JSON(), nullable=True),
    sa.Column("processor_token", sa.String(length=200), nullable=True),
    sa.Column("received_at", sa.DateTime(), nullable=False),
    sa.Column("processed_at", sa.DateTime(), nullable=True),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(["command_id"], ["wes_biz.device_commands.id"], ),
    sa.ForeignKeyConstraint(["device_id"], ["wes_biz.devices.id"], ),
    sa.ForeignKeyConstraint(["session_id"], ["wes_biz.workline_sessions.id"], ),
    sa.ForeignKeyConstraint(["workline_id"], ["wes_biz.work_lines.id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.Column("kind", sa.Enum("DEVICE_EVENT", "EXTERNAL_HTTP", "TIMER_TIMEOUT", "MANUAL_HOLD", "MANUAL_RESUME", "MANUAL_CANCEL", "REPLAY_REQUEST", name="inboxkind", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("source_system", sa.Enum("DEVICE", "WCS", "MES", "ERP", "MANUAL", "SYSTEM", name="sourcesystem", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("status", sa.Enum("NEW", "PROCESSING", "PROCESSED", "FAILED", name="inboxstatus", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_workline_inbox_command_id"), "workline_inbox", ["command_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_correlation_id"), "workline_inbox", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_device_id"), "workline_inbox", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_id"), "workline_inbox", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_idempotency_key"), "workline_inbox", ["idempotency_key"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_kind"), "workline_inbox", ["kind"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_received_at"), "workline_inbox", ["received_at"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_session_id"), "workline_inbox", ["session_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_source_system"), "workline_inbox", ["source_system"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_status"), "workline_inbox", ["status"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_inbox_workline_id"), "workline_inbox", ["workline_id"], unique=False, schema="wes_biz")
    op.create_table("workline_timelines",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("session_id", sa.Integer(), nullable=False),
    sa.Column("workline_id", sa.Integer(), nullable=False),
    sa.Column("correlation_id", sa.String(length=100), nullable=True),
    sa.Column("seq_no", sa.Integer(), nullable=False),
    sa.Column("occurred_at", sa.DateTime(), nullable=False),
    sa.Column("actor_code", sa.String(length=100), nullable=True),
    sa.Column("from_status", sa.String(length=50), nullable=True),
    sa.Column("to_status", sa.String(length=50), nullable=True),
    sa.Column("failure_domain", sa.String(length=100), nullable=True),
    sa.Column("message", sa.Text(), nullable=True),
    sa.Column("payload_json", sa.JSON(), nullable=True),
    sa.Column("related_inbox_id", sa.Integer(), nullable=True),
    sa.Column("related_event_log_id", sa.Integer(), nullable=True),
    sa.Column("related_command_id", sa.Integer(), nullable=True),
    sa.Column("related_external_call_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["related_command_id"], ["wes_biz.device_commands.id"], ),
    sa.ForeignKeyConstraint(["related_event_log_id"], ["wes_biz.device_event_logs.id"], ),
    sa.ForeignKeyConstraint(["session_id"], ["wes_biz.workline_sessions.id"], ),
    sa.ForeignKeyConstraint(["workline_id"], ["wes_biz.work_lines.id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.Column("stage", sa.Enum("INGEST", "ROUTE", "DECISION", "DISPATCH_PREPARE", "WAITING", "CALLBACK", "MANUAL", "TIMEOUT", "COMPENSATION", "COMPLETE", "FAIL", name="timelinestage", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("action_type", sa.Enum("SESSION_CREATED", "SESSION_STARTED", "SESSION_RESUMED", "SESSION_COMPLETED", "SESSION_FAILED", "SESSION_CANCELLED", "STATUS_CHANGED", "WAIT_STARTED", "WAIT_RESUMED", "WAIT_TIMEOUT", "COMMAND_SENT", "COMMAND_ACKED", "COMMAND_COMPLETED", "COMMAND_FAILED", "EVENT_RECEIVED", "EVENT_PROCESSED", "EVENT_FAILED", "EXTERNAL_CALL_STARTED", "EXTERNAL_CALL_COMPLETED", "EXTERNAL_CALL_FAILED", "DECISION_MADE", "ERROR_OCCURRED", "COMPENSATION_STARTED", "COMPENSATION_COMPLETED", "MANUAL_HOLD", "MANUAL_RESUME", name="timelineactiontype", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("actor_type", sa.Enum("PLUGIN", "DEVICE", "EXTERNAL_SYSTEM", "ORCHESTRATOR", "MANUAL_OPERATOR", name="timelineactortype", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("status", sa.Enum("SUCCESS", "FAILED", "PENDING", name="timelinestatus", schema="wes_biz", native_enum=False, create_constraint=True, length=50), nullable=False),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_workline_timelines_action_type"), "workline_timelines", ["action_type"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_correlation_id"), "workline_timelines", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_id"), "workline_timelines", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_occurred_at"), "workline_timelines", ["occurred_at"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_seq_no"), "workline_timelines", ["seq_no"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_session_id"), "workline_timelines", ["session_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_stage"), "workline_timelines", ["stage"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_status"), "workline_timelines", ["status"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_workline_timelines_workline_id"), "workline_timelines", ["workline_id"], unique=False, schema="wes_biz")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wes_biz_workline_timelines_workline_id"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_status"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_stage"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_session_id"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_seq_no"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_occurred_at"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_id"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_correlation_id"), table_name="workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_timelines_action_type"), table_name="workline_timelines", schema="wes_biz")
    op.drop_table("workline_timelines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_workline_id"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_status"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_source_system"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_session_id"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_received_at"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_kind"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_idempotency_key"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_id"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_device_id"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_correlation_id"), table_name="workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_inbox_command_id"), table_name="workline_inbox", schema="wes_biz")
    op.drop_table("workline_inbox", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_workline_id"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_status"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_started_at"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_session_code"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_plugin_key"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_id"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_correlation_id"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_business_key"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_barcode"), table_name="workline_sessions", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_workline_sessions_awaiting_command_id"), table_name="workline_sessions", schema="wes_biz")
    op.drop_table("workline_sessions", schema="wes_biz")
    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.timelinestatus CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.timelinestage CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.timelineactortype CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.timelineactiontype CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.targettype CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.sourcesystem CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.sessionstatus CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.runmode CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.outboxstatus CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.inboxstatus CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.inboxkind CASCADE")

    # 删除 ENUM 类型
    op.execute("DROP TYPE IF EXISTS wes_biz.dispatchtype CASCADE")

        # ### end Alembic commands ###
