"""Initial migration - all models with VARCHAR + CHECK constraints

Revision ID: be330a8cda0a
Revises: 
Create Date: 2026-03-16 20:40:53.406692+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be330a8cda0a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("demo_products",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("name", sa.String(length=100), nullable=False, comment="产品名称"),
    sa.Column("price", sa.Float(), nullable=False),
    sa.Column("stock", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index("demo_products_name_active_unique", "demo_products", ["name"], unique=True, schema="wes_biz", postgresql_where="NOT is_deleted")
    op.create_index(op.f("ix_wes_biz_demo_products_id"), "demo_products", ["id"], unique=True, schema="wes_biz")
    op.create_table("work_lines",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("line_code", sa.String(length=50), nullable=False),
    sa.Column("line_name", sa.String(length=100), nullable=False),
    sa.Column("line_type", sa.Enum("AUTO", "MANUAL", "HYBRID", name="linetype", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("zone_name", sa.String(length=100), nullable=True),
    sa.Column("description", sa.String(length=500), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("capacity", sa.Integer(), nullable=True),
    sa.Column("sort_order", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_work_lines_id"), "work_lines", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_work_lines_line_code"), "work_lines", ["line_code"], unique=False, schema="wes_biz")
    op.create_table("api_access_logs",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("app_id", sa.String(length=50), nullable=False),
    sa.Column("app_name", sa.String(length=100), nullable=False),
    sa.Column("request_id", sa.String(length=50), nullable=False),
    sa.Column("method", sa.String(length=10), nullable=False),
    sa.Column("path", sa.String(length=500), nullable=False),
    sa.Column("status_code", sa.Integer(), nullable=False),
    sa.Column("response_time_ms", sa.Integer(), nullable=False),
    sa.Column("ip_address", sa.String(length=50), nullable=False),
    sa.Column("user_agent", sa.String(length=500), nullable=True),
    sa.Column("error_message", sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index("ix_api_access_log_app_time", "api_access_logs", ["app_id", "created_at"], unique=False, schema="wes_sys")
    op.create_index("ix_api_access_log_path", "api_access_logs", ["path", "created_at"], unique=False, schema="wes_sys", postgresql_ops={"path": "text_pattern_ops"})
    op.create_index("ix_api_access_log_status", "api_access_logs", ["status_code", "created_at"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_api_access_logs_id"), "api_access_logs", ["id"], unique=True, schema="wes_sys")
    op.create_table("api_applications",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("app_name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=500), nullable=True),
    sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
    sa.Column("rate_limit_per_hour", sa.Integer(), nullable=False),
    sa.Column("app_type", sa.Enum("ECS", "RCS", "WMS", "ThirdParty", name="apptype", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("validity_period", sa.Enum("ONE_DAY", "ONE_WEEK", "ONE_MONTH", "SIX_MONTHS", "ONE_YEAR", "NEVER", name="validityperiod", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("ip_whitelist", sa.JSON(), nullable=True),
    sa.Column("app_id", sa.String(length=50), nullable=False),
    sa.Column("app_secret_encrypted", sa.String(length=500), nullable=False),
    sa.Column("status", sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="appstatus", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index("ix_api_applications_app_id", "api_applications", ["app_id", "is_deleted"], unique=True, schema="wes_sys", postgresql_where="NOT is_deleted")
    op.create_index("ix_api_applications_id", "api_applications", ["id"], unique=True, schema="wes_sys")
    op.create_index("ix_api_applications_status", "api_applications", ["status", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index("ix_api_applications_type", "api_applications", ["app_type", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_api_applications_id"), "api_applications", ["id"], unique=True, schema="wes_sys")
    op.create_table("audit_logs",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("trace_id", sa.String(length=64), nullable=False),
    sa.Column("username", sa.String(length=32), nullable=True),
    sa.Column("method", sa.String(length=10), nullable=False),
    sa.Column("title", sa.String(length=100), nullable=False),
    sa.Column("path", sa.String(length=200), nullable=False),
    sa.Column("ip", sa.String(length=64), nullable=False),
    sa.Column("country", sa.String(length=64), nullable=True),
    sa.Column("region", sa.String(length=64), nullable=True),
    sa.Column("city", sa.String(length=64), nullable=True),
    sa.Column("user_agent", sa.String(length=500), nullable=False),
    sa.Column("os", sa.String(length=64), nullable=True),
    sa.Column("browser", sa.String(length=64), nullable=True),
    sa.Column("device", sa.String(length=64), nullable=True),
    sa.Column("args", sa.JSON(), nullable=True),
    sa.Column("status", sa.Enum("FAIL", "SUCCESS", name="operastatus", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("code", sa.String(length=20), nullable=False),
    sa.Column("msg", sa.Text(), nullable=True),
    sa.Column("cost_time", sa.Float(), nullable=False),
    sa.Column("opera_time", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_audit_logs_id"), "audit_logs", ["id"], unique=True, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_audit_logs_opera_time"), "audit_logs", ["opera_time"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_audit_logs_trace_id"), "audit_logs", ["trace_id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_audit_logs_username"), "audit_logs", ["username"], unique=False, schema="wes_sys")
    op.create_table("menus",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("parent_id", sa.Integer(), nullable=True, comment="父节点ID"),
    sa.Column("tree_path", sa.String(), nullable=False, comment="节点路径"),
    sa.Column("level", sa.Integer(), nullable=False, comment="节点层级"),
    sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序号"),
    sa.Column("name", sa.String(length=50), nullable=False),
    sa.Column("title", sa.String(length=50), nullable=False),
    sa.Column("path", sa.String(length=200), nullable=False),
    sa.Column("component", sa.String(length=200), nullable=True),
    sa.Column("icon", sa.String(length=50), nullable=True),
    sa.Column("is_hidden", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_menus_id"), "menus", ["id"], unique=True, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_menus_parent_id"), "menus", ["parent_id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_menus_tree_path"), "menus", ["tree_path"], unique=False, schema="wes_sys")
    op.create_index("ux_menus_name_deleted", "menus", ["name"], unique=True, schema="wes_sys", postgresql_where="NOT is_deleted")
    op.create_table("permissions",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("parent_id", sa.Integer(), nullable=True),
    sa.Column("tree_path", sa.String(), nullable=False, comment="节点路径"),
    sa.Column("level", sa.Integer(), nullable=False, comment="节点层级"),
    sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序号"),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.Column("type", sa.String(length=20), nullable=False),
    sa.Column("category", sa.String(length=50), nullable=True),
    sa.Column("resource", sa.String(length=50), nullable=True),
    sa.Column("action", sa.String(length=50), nullable=True),
    sa.Column("method", sa.String(length=10), nullable=True),
    sa.Column("path", sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(["parent_id"], ["wes_sys.permissions.id"], ),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index("ix_perm_api_deleted", "permissions", ["method", "path", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index("ix_perm_parent_sort_deleted", "permissions", ["parent_id", "sort_order", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index("ix_perm_type_deleted", "permissions", ["type", "is_deleted"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_id"), "permissions", ["id"], unique=True, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_parent_id"), "permissions", ["parent_id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_tree_path"), "permissions", ["tree_path"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_permissions_type"), "permissions", ["type"], unique=False, schema="wes_sys")
    op.create_index("ux_perm_name_deleted", "permissions", ["name"], unique=True, schema="wes_sys", postgresql_where="NOT is_deleted")
    op.create_table("roles",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_roles_id"), "roles", ["id"], unique=True, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_roles_name"), "roles", ["name"], unique=False, schema="wes_sys")
    op.create_index("ux_roles_name_deleted", "roles", ["name"], unique=True, schema="wes_sys", postgresql_where="NOT is_deleted")
    op.create_table("users",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("username", sa.String(length=50), nullable=False),
    sa.Column("email", sa.String(length=100), nullable=False),
    sa.Column("full_name", sa.String(length=100), nullable=True),
    sa.Column("hashed_password", sa.String(length=255), nullable=False),
    sa.Column("is_superuser", sa.Boolean(), nullable=False),
    sa.Column("is_multi_login", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_users_email"), "users", ["email"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_users_id"), "users", ["id"], unique=True, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_users_username"), "users", ["username"], unique=False, schema="wes_sys")
    op.create_index("ux_users_email_deleted", "users", ["email"], unique=True, schema="wes_sys", postgresql_where=sa.text("NOT is_deleted"), sqlite_where=sa.text("NOT is_deleted"))
    op.create_index("ux_users_username_deleted", "users", ["username"], unique=True, schema="wes_sys", postgresql_where=sa.text("NOT is_deleted"), sqlite_where=sa.text("NOT is_deleted"))
    op.create_table("demo_product_lists",
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("product_id", sa.BigInteger(), nullable=True),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["product_id"], ["wes_biz.demo_products.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_demo_product_lists_id"), "demo_product_lists", ["id"], unique=True, schema="wes_biz")
    op.create_table("devices",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("device_code", sa.String(length=50), nullable=False),
    sa.Column("device_name", sa.String(length=100), nullable=False),
    sa.Column("device_type", sa.Enum("PDA", "INDUSTRIAL_PC", "PRINTER", "COMPUTER", "LCR_TESTER", "ROBOTIC_ARM", "VISION_CAMERA", "CONVEYOR", "LABELER", "XRAY", "SCANNER", name="devicetype", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("work_line_id", sa.Integer(), nullable=True),
    sa.Column("description", sa.String(length=500), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("sort_order", sa.Integer(), nullable=False),
    sa.Column("device_role", sa.String(length=50), nullable=False),
    sa.Column("role_index", sa.Integer(), nullable=False),
    sa.Column("upstream_device_id", sa.Integer(), nullable=True),
    sa.Column("vendor_type", sa.String(length=50), nullable=True),
    sa.Column("capabilities", sa.JSON(), nullable=True),
    sa.Column("host", sa.String(length=100), nullable=True),
    sa.Column("port", sa.Integer(), nullable=True),
    sa.Column("protocol", sa.Enum("HTTP", "HTTPS", "TCP", "MODBUS", "MQTT", name="deviceprotocol", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("auth_token", sa.String(length=500), nullable=True),
    sa.Column("timeout", sa.Integer(), nullable=False),
    sa.Column("device_status", sa.Enum("IDLE", "RUNNING", "ERROR", "OFFLINE", name="devicestatus", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("current_command_id", sa.Integer(), nullable=True),
    sa.Column("last_heartbeat_at", sa.DateTime(), nullable=True),
    sa.Column("error_code", sa.String(length=50), nullable=True),
    sa.Column("supported_commands", sa.JSON(), nullable=True),
    sa.Column("max_concurrent_tasks", sa.Integer(), nullable=False),
    sa.Column("idempotency_ttl", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["upstream_device_id"], ["wes_biz.devices.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["work_line_id"], ["wes_biz.work_lines.id"], ),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_devices_device_code"), "devices", ["device_code"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_devices_id"), "devices", ["id"], unique=True, schema="wes_biz")
    op.create_index("ux_devices_device_code_deleted", "devices", ["device_code"], unique=True, schema="wes_biz", postgresql_where="NOT is_deleted")
    op.create_table("api_app_permissions",
    sa.Column("app_id", sa.BigInteger(), nullable=False),
    sa.Column("permission_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["app_id"], ["wes_sys.api_applications.id"], name=op.f("fk_api_app_permissions_app_id_api_applications"), ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["permission_id"], ["wes_sys.permissions.id"], name=op.f("fk_api_app_permissions_permission_id_permissions"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("app_id", "permission_id", name=op.f("pk_api_app_permissions")),
    schema="wes_sys"
    )
    op.create_table("role_menus",
    sa.Column("role_id", sa.BigInteger(), nullable=False),
    sa.Column("menu_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["menu_id"], ["wes_sys.menus.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["role_id"], ["wes_sys.roles.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("role_id", "menu_id"),
    schema="wes_sys",
    comment="角色-菜单关联表"
    )
    op.create_table("role_permissions",
    sa.Column("role_id", sa.BigInteger(), nullable=False),
    sa.Column("permission_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["permission_id"], ["wes_sys.permissions.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["role_id"], ["wes_sys.roles.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("role_id", "permission_id"),
    schema="wes_sys",
    comment="角色-权限关联表"
    )
    op.create_table("user_roles",
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.Column("role_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["role_id"], ["wes_sys.roles.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["wes_sys.users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("user_id", "role_id"),
    schema="wes_sys",
    comment="用户-角色关联表"
    )
    op.create_table("device_commands",
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("device_id", sa.Integer(), nullable=False),
    sa.Column("task_type", sa.Enum("PICK", "PUT", "SCAN", "ROTATE", "PROCESS", "PICK_AND_PLACE", name="tasktype", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("priority", sa.Integer(), nullable=False),
    sa.Column("timeout_ms", sa.Integer(), nullable=False),
    sa.Column("params", sa.JSON(), nullable=True),
    sa.Column("command_code", sa.String(length=100), nullable=False),
    sa.Column("correlation_id", sa.String(length=100), nullable=True),
    sa.Column("status", sa.Enum("PENDING", "SENT", "ACK_RECEIVED", "COMPLETED", "FAILED", "TIMEOUT", "CANCELLED", name="commandstatus", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("sent_at", sa.DateTime(), nullable=True),
    sa.Column("ack_received_at", sa.DateTime(), nullable=True),
    sa.Column("completed_at", sa.DateTime(), nullable=True),
    sa.Column("result", sa.Enum("SUCCESS", "FAILED", name="commandresult", native_enum=False, create_constraint=True, length=50), nullable=True),
    sa.Column("result_data", sa.JSON(), nullable=True),
    sa.Column("error_detail", sa.JSON(), nullable=True),
    sa.Column("retry_count", sa.Integer(), nullable=False),
    sa.Column("ack_code", sa.Integer(), nullable=True),
    sa.Column("ack_message", sa.String(length=500), nullable=True),
    sa.Column("ack_trace_id", sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(["device_id"], ["wes_biz.devices.id"], ),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_device_commands_command_code"), "device_commands", ["command_code"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_correlation_id"), "device_commands", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_device_id"), "device_commands", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_id"), "device_commands", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_status"), "device_commands", ["status"], unique=False, schema="wes_biz")
    op.create_table("device_event_logs",
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("device_id", sa.Integer(), nullable=False),
    sa.Column("event_type", sa.Enum("ESTOP_PRESSED", "DEVICE_ONLINE", "DEVICE_OFFLINE", "DEVICE_ERROR", "MATERIAL_ARRIVED", "SCAN_COMPLETED", "PICK_COMPLETED", "PUT_COMPLETED", "PROCESS_COMPLETED", name="eventtype", native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column("event_timestamp", sa.DateTime(), nullable=False),
    sa.Column("event_data", sa.JSON(), nullable=True),
    sa.Column("processed", sa.Boolean(), nullable=False),
    sa.Column("processing_result", sa.JSON(), nullable=True),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("correlation_id", sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(["device_id"], ["wes_biz.devices.id"], ),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_device_event_logs_correlation_id"), "device_event_logs", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_device_id"), "device_event_logs", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_event_timestamp"), "device_event_logs", ["event_timestamp"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_event_type"), "device_event_logs", ["event_type"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_id"), "device_event_logs", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_processed"), "device_event_logs", ["processed"], unique=False, schema="wes_biz")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wes_biz_device_event_logs_processed"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_event_type"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_event_timestamp"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_device_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_correlation_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_table("device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_status"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_device_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_correlation_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_command_code"), table_name="device_commands", schema="wes_biz")
    op.drop_table("device_commands", schema="wes_biz")
    op.drop_table("user_roles", schema="wes_sys")
    op.drop_table("role_permissions", schema="wes_sys")
    op.drop_table("role_menus", schema="wes_sys")
    op.drop_table("api_app_permissions", schema="wes_sys")
    op.drop_index("ux_devices_device_code_deleted", table_name="devices", schema="wes_biz", postgresql_where="NOT is_deleted")
    op.drop_index(op.f("ix_wes_biz_devices_id"), table_name="devices", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_devices_device_code"), table_name="devices", schema="wes_biz")
    op.drop_table("devices", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_demo_product_lists_id"), table_name="demo_product_lists", schema="wes_biz")
    op.drop_table("demo_product_lists", schema="wes_biz")
    op.drop_index("ux_users_username_deleted", table_name="users", schema="wes_sys", postgresql_where=sa.text("NOT is_deleted"), sqlite_where=sa.text("NOT is_deleted"))
    op.drop_index("ux_users_email_deleted", table_name="users", schema="wes_sys", postgresql_where=sa.text("NOT is_deleted"), sqlite_where=sa.text("NOT is_deleted"))
    op.drop_index(op.f("ix_wes_sys_users_username"), table_name="users", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_users_id"), table_name="users", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_users_email"), table_name="users", schema="wes_sys")
    op.drop_table("users", schema="wes_sys")
    op.drop_index("ux_roles_name_deleted", table_name="roles", schema="wes_sys", postgresql_where="NOT is_deleted")
    op.drop_index(op.f("ix_wes_sys_roles_name"), table_name="roles", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_roles_id"), table_name="roles", schema="wes_sys")
    op.drop_table("roles", schema="wes_sys")
    op.drop_index("ux_perm_name_deleted", table_name="permissions", schema="wes_sys", postgresql_where="NOT is_deleted")
    op.drop_index(op.f("ix_wes_sys_permissions_type"), table_name="permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_permissions_tree_path"), table_name="permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_permissions_parent_id"), table_name="permissions", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_permissions_id"), table_name="permissions", schema="wes_sys")
    op.drop_index("ix_perm_type_deleted", table_name="permissions", schema="wes_sys")
    op.drop_index("ix_perm_parent_sort_deleted", table_name="permissions", schema="wes_sys")
    op.drop_index("ix_perm_api_deleted", table_name="permissions", schema="wes_sys")
    op.drop_table("permissions", schema="wes_sys")
    op.drop_index("ux_menus_name_deleted", table_name="menus", schema="wes_sys", postgresql_where="NOT is_deleted")
    op.drop_index(op.f("ix_wes_sys_menus_tree_path"), table_name="menus", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_menus_parent_id"), table_name="menus", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_menus_id"), table_name="menus", schema="wes_sys")
    op.drop_table("menus", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_username"), table_name="audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_trace_id"), table_name="audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_opera_time"), table_name="audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_audit_logs_id"), table_name="audit_logs", schema="wes_sys")
    op.drop_table("audit_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_api_applications_id"), table_name="api_applications", schema="wes_sys")
    op.drop_index("ix_api_applications_type", table_name="api_applications", schema="wes_sys")
    op.drop_index("ix_api_applications_status", table_name="api_applications", schema="wes_sys")
    op.drop_index("ix_api_applications_id", table_name="api_applications", schema="wes_sys")
    op.drop_index("ix_api_applications_app_id", table_name="api_applications", schema="wes_sys", postgresql_where="NOT is_deleted")
    op.drop_table("api_applications", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_api_access_logs_id"), table_name="api_access_logs", schema="wes_sys")
    op.drop_index("ix_api_access_log_status", table_name="api_access_logs", schema="wes_sys")
    op.drop_index("ix_api_access_log_path", table_name="api_access_logs", schema="wes_sys", postgresql_ops={"path": "text_pattern_ops"})
    op.drop_index("ix_api_access_log_app_time", table_name="api_access_logs", schema="wes_sys")
    op.drop_table("api_access_logs", schema="wes_sys")
    op.drop_index(op.f("ix_wes_biz_work_lines_line_code"), table_name="work_lines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_work_lines_id"), table_name="work_lines", schema="wes_biz")
    op.drop_table("work_lines", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_demo_products_id"), table_name="demo_products", schema="wes_biz")
    op.drop_index("demo_products_name_active_unique", table_name="demo_products", schema="wes_biz", postgresql_where="NOT is_deleted")
    op.drop_table("demo_products", schema="wes_biz")
    # ### end Alembic commands ###
