"""优化 Device 模型, 加入白皮书通信配置

Revision ID: d967fe93d0f3
Revises: 17dae3be98cf
Create Date: 2026-03-04 13:52:25.962924+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d967fe93d0f3"
down_revision: Union[str, Sequence[str], None] = "17dae3be98cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_callback_logs_callback_type"), table_name="callback_logs", schema="wes_biz")
    op.drop_index(op.f("ix_callback_logs_correlation_id"), table_name="callback_logs", schema="wes_biz")
    op.drop_index(op.f("ix_callback_logs_device_id"), table_name="callback_logs", schema="wes_biz")
    op.drop_index(op.f("ix_callback_logs_request_id"), table_name="callback_logs", schema="wes_biz")
    op.drop_table("callback_logs", schema="wes_biz")
    op.alter_column("device_commands", "deleted_by",
               existing_type=sa.INTEGER(),
               comment="删除人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "deleted_at",
               existing_type=postgresql.TIMESTAMP(),
               comment="删除时间",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "is_deleted",
               existing_type=sa.BOOLEAN(),
               comment="是否已删除",
               existing_nullable=False,
               existing_server_default=sa.text("false"),
               schema="wes_biz")
    op.alter_column("device_commands", "version",
               existing_type=sa.INTEGER(),
               comment="版本号",
               existing_nullable=False,
               existing_server_default=sa.text("0"),
               schema="wes_biz")
    op.alter_column("device_commands", "created_at",
               existing_type=postgresql.TIMESTAMP(),
               comment="创建时间 (UTC)",
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "updated_at",
               existing_type=postgresql.TIMESTAMP(),
               comment="更新时间 (UTC)",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "created_by",
               existing_type=sa.BIGINT(),
               comment="创建人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "updated_by",
               existing_type=sa.BIGINT(),
               comment="更新人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "id",
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment="主键 ID",
               existing_nullable=False,
               autoincrement=True,
               schema="wes_biz")
    # task_type: PostgreSQL ENUM 类型转换（使用 USING 避免类型不兼容错误）
    op.execute("ALTER TABLE wes_biz.device_commands ALTER COLUMN task_type TYPE wes_biz.tasktype USING task_type::text::wes_biz.tasktype")
    op.alter_column("device_commands", "priority",
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "timeout_ms",
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "params",
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               schema="wes_biz")
    # status: PostgreSQL ENUM 类型转换
    op.execute("ALTER TABLE wes_biz.device_commands ALTER COLUMN status TYPE wes_biz.commandstatus USING status::text::wes_biz.commandstatus")
    # result: PostgreSQL ENUM 类型转换
    op.execute("ALTER TABLE wes_biz.device_commands ALTER COLUMN result TYPE wes_biz.commandresult USING result::text::wes_biz.commandresult")
    op.alter_column("device_commands", "result_data",
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "retry_count",
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.drop_constraint(op.f("device_commands_command_id_key"), "device_commands", schema="wes_biz", type_="unique")
    op.drop_index(op.f("ix_device_commands_command_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_device_commands_correlation_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_device_commands_device_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_device_commands_status"), table_name="device_commands", schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_command_id"), "device_commands", ["command_id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_correlation_id"), "device_commands", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_device_id"), "device_commands", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_id"), "device_commands", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_status"), "device_commands", ["status"], unique=False, schema="wes_biz")
    # 注意：外键将在 device_code 添加唯一约束后创建
    # op.create_foreign_key(None, "device_commands", "devices", ["device_id"], ["device_code"], source_schema="wes_biz", referent_schema="wes_biz")
    op.drop_table_comment(
        "device_commands",
        existing_comment="设备指令",
        schema="wes_biz"
    )
    op.alter_column("device_event_logs", "deleted_by",
               existing_type=sa.INTEGER(),
               comment="删除人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "deleted_at",
               existing_type=postgresql.TIMESTAMP(),
               comment="删除时间",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "is_deleted",
               existing_type=sa.BOOLEAN(),
               comment="是否已删除",
               existing_nullable=False,
               existing_server_default=sa.text("false"),
               schema="wes_biz")
    op.alter_column("device_event_logs", "created_at",
               existing_type=postgresql.TIMESTAMP(),
               comment="创建时间 (UTC)",
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_event_logs", "updated_at",
               existing_type=postgresql.TIMESTAMP(),
               comment="更新时间 (UTC)",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "id",
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment="主键 ID",
               existing_nullable=False,
               autoincrement=True,
               schema="wes_biz")
    # event_type: PostgreSQL ENUM 类型转换
    op.execute("ALTER TABLE wes_biz.device_event_logs ALTER COLUMN event_type TYPE wes_biz.eventtype USING event_type::text::wes_biz.eventtype")
    op.alter_column("device_event_logs", "event_data",
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "processed",
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_event_logs", "processing_result",
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema="wes_biz")
    op.drop_index(op.f("ix_device_event_logs_correlation_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_device_event_logs_device_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_device_event_logs_event_type"), table_name="device_event_logs", schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_correlation_id"), "device_event_logs", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_device_id"), "device_event_logs", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_event_timestamp"), "device_event_logs", ["event_timestamp"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_event_type"), "device_event_logs", ["event_type"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_id"), "device_event_logs", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_processed"), "device_event_logs", ["processed"], unique=False, schema="wes_biz")
    # 注意：外键将在 device_code 添加唯一约束后创建
    # op.create_foreign_key(None, "device_event_logs", "devices", ["device_id"], ["device_code"], source_schema="wes_biz", referent_schema="wes_biz")
    op.drop_table_comment(
        "device_event_logs",
        existing_comment="设备事件日志",
        schema="wes_biz"
    )
    op.drop_column("device_event_logs", "version", schema="wes_biz")
    op.drop_column("device_event_logs", "updated_by", schema="wes_biz")
    op.drop_column("device_event_logs", "created_by", schema="wes_biz")
    op.add_column("devices", sa.Column("host", sa.String(length=100), nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("port", sa.Integer(), nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("protocol", sa.String(length=10), server_default="HTTP", nullable=False), schema="wes_biz")
    op.add_column("devices", sa.Column("auth_token", sa.String(length=500), nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("timeout", sa.Integer(), server_default="10000", nullable=False), schema="wes_biz")
    op.add_column("devices", sa.Column("device_status", sa.String(length=20), server_default="IDLE", nullable=False), schema="wes_biz")
    op.add_column("devices", sa.Column("current_command_id", sa.String(length=100), nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("last_heartbeat_at", sa.DateTime(), nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("error_code", sa.String(length=50), nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("supported_commands", sa.JSON(), nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("max_concurrent_tasks", sa.Integer(), server_default="1", nullable=False), schema="wes_biz")
    op.add_column("devices", sa.Column("idempotency_ttl", sa.Integer(), server_default="3600", nullable=False), schema="wes_biz")
    # api_applications: PostgreSQL ENUM 类型转换
    op.execute("ALTER TABLE wes_sys.api_applications ALTER COLUMN app_type TYPE wes_sys.apptype USING app_type::text::wes_sys.apptype")
    op.execute("ALTER TABLE wes_sys.api_applications ALTER COLUMN validity_period TYPE wes_sys.validityperiod USING validity_period::text::wes_sys.validityperiod")
    op.execute("ALTER TABLE wes_sys.api_applications ALTER COLUMN status TYPE wes_sys.appstatus USING status::text::wes_sys.appstatus")
    # audit_logs: PostgreSQL ENUM 类型转换
    op.execute("ALTER TABLE wes_sys.audit_logs ALTER COLUMN status TYPE wes_sys.operastatus USING status::text::wes_sys.operastatus")
    op.drop_table_comment(
        "permissions",
        existing_comment="API 权限表（仅用于后端 API 访问控制）",
        schema="wes_sys"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "permissions",
        "API 权限表（仅用于后端 API 访问控制）",
        existing_comment=None,
        schema="wes_sys"
    )
    # api_applications 和 audit_logs: PostgreSQL ENUM 类型转换（downgrade）
    op.execute("ALTER TABLE wes_sys.audit_logs ALTER COLUMN status TYPE wes_sys.operastatus USING status::text::wes_sys.operastatus")
    op.execute("ALTER TABLE wes_sys.api_applications ALTER COLUMN status TYPE wes_sys.appstatus USING status::text::wes_sys.appstatus")
    op.execute("ALTER TABLE wes_sys.api_applications ALTER COLUMN validity_period TYPE wes_sys.validityperiod USING validity_period::text::wes_sys.validityperiod")
    op.execute("ALTER TABLE wes_sys.api_applications ALTER COLUMN app_type TYPE wes_sys.apptype USING app_type::text::wes_sys.apptype")
    op.drop_column("devices", "idempotency_ttl", schema="wes_biz")
    op.drop_column("devices", "max_concurrent_tasks", schema="wes_biz")
    op.drop_column("devices", "supported_commands", schema="wes_biz")
    op.drop_column("devices", "error_code", schema="wes_biz")
    op.drop_column("devices", "last_heartbeat_at", schema="wes_biz")
    op.drop_column("devices", "current_command_id", schema="wes_biz")
    op.drop_column("devices", "device_status", schema="wes_biz")
    op.drop_column("devices", "timeout", schema="wes_biz")
    op.drop_column("devices", "auth_token", schema="wes_biz")
    op.drop_column("devices", "protocol", schema="wes_biz")
    op.drop_column("devices", "port", schema="wes_biz")
    op.drop_column("devices", "host", schema="wes_biz")
    op.add_column("device_event_logs", sa.Column("created_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="wes_biz")
    op.add_column("device_event_logs", sa.Column("updated_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="wes_biz")
    op.add_column("device_event_logs", sa.Column("version", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False), schema="wes_biz")
    op.create_table_comment(
        "device_event_logs",
        "设备事件日志",
        existing_comment=None,
        schema="wes_biz"
    )
    # 注意：外键未创建，无需删除
    # op.drop_constraint(None, "device_event_logs", schema="wes_biz", type_="foreignkey")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_processed"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_event_type"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_event_timestamp"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_device_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_correlation_id"), table_name="device_event_logs", schema="wes_biz")
    op.create_index(op.f("ix_device_event_logs_event_type"), "device_event_logs", ["event_type"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_device_event_logs_device_id"), "device_event_logs", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_device_event_logs_correlation_id"), "device_event_logs", ["correlation_id"], unique=False, schema="wes_biz")
    op.alter_column("device_event_logs", "processing_result",
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "processed",
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("false"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_event_logs", "event_data",
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema="wes_biz")
    # event_type: PostgreSQL ENUM 类型转换（downgrade）
    op.execute("ALTER TABLE wes_biz.device_event_logs ALTER COLUMN event_type TYPE wes_biz.eventtype USING event_type::text::wes_biz.eventtype")
    op.alter_column("device_event_logs", "id",
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment="主键 ID",
               existing_nullable=False,
               autoincrement=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "updated_at",
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="更新时间 (UTC)",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "created_at",
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="创建时间 (UTC)",
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_event_logs", "is_deleted",
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="是否已删除",
               existing_nullable=False,
               existing_server_default=sa.text("false"),
               schema="wes_biz")
    op.alter_column("device_event_logs", "deleted_at",
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="删除时间",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_event_logs", "deleted_by",
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="删除人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.create_table_comment(
        "device_commands",
        "设备指令",
        existing_comment=None,
        schema="wes_biz"
    )
    # 注意：外键未创建，无需删除
    # op.drop_constraint(None, "device_commands", schema="wes_biz", type_="foreignkey")
    op.drop_index(op.f("ix_wes_biz_device_commands_status"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_device_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_correlation_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_command_id"), table_name="device_commands", schema="wes_biz")
    op.create_index(op.f("ix_device_commands_status"), "device_commands", ["status"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_device_commands_device_id"), "device_commands", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_device_commands_correlation_id"), "device_commands", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_device_commands_command_id"), "device_commands", ["command_id"], unique=False, schema="wes_biz")
    op.create_unique_constraint(op.f("device_commands_command_id_key"), "device_commands", ["command_id"], schema="wes_biz", postgresql_nulls_not_distinct=False)
    op.alter_column("device_commands", "retry_count",
               existing_type=sa.INTEGER(),
               server_default=sa.text("0"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "result_data",
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema="wes_biz")
    # result: PostgreSQL ENUM 类型转换（downgrade）
    op.execute("ALTER TABLE wes_biz.device_commands ALTER COLUMN result TYPE wes_biz.commandresult USING result::text::wes_biz.commandresult")
    # status: PostgreSQL ENUM 类型转换（downgrade）
    op.execute("ALTER TABLE wes_biz.device_commands ALTER COLUMN status TYPE wes_biz.commandstatus USING status::text::wes_biz.commandstatus")
    op.alter_column("device_commands", "params",
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "timeout_ms",
               existing_type=sa.INTEGER(),
               server_default=sa.text("30000"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "priority",
               existing_type=sa.INTEGER(),
               server_default=sa.text("5"),
               existing_nullable=False,
               schema="wes_biz")
    # task_type: PostgreSQL ENUM 类型转换（downgrade）
    op.execute("ALTER TABLE wes_biz.device_commands ALTER COLUMN task_type TYPE wes_biz.tasktype USING task_type::text::wes_biz.tasktype")
    op.alter_column("device_commands", "id",
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment="主键 ID",
               existing_nullable=False,
               autoincrement=True,
               schema="wes_biz")
    op.alter_column("device_commands", "updated_by",
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment="更新人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "created_by",
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment="创建人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "updated_at",
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="更新时间 (UTC)",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "created_at",
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="创建时间 (UTC)",
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "version",
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="版本号",
               existing_nullable=False,
               existing_server_default=sa.text("0"),
               schema="wes_biz")
    op.alter_column("device_commands", "is_deleted",
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="是否已删除",
               existing_nullable=False,
               existing_server_default=sa.text("false"),
               schema="wes_biz")
    op.alter_column("device_commands", "deleted_at",
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="删除时间",
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "deleted_by",
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="删除人ID",
               existing_nullable=True,
               schema="wes_biz")
    op.create_table("callback_logs",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column("is_deleted", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=True),
    sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True),
    sa.Column("updated_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True),
    sa.Column("callback_type", sa.VARCHAR(), autoincrement=False, nullable=False, comment="回调类型: event/result"),
    sa.Column("device_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="设备 ID"),
    sa.Column("request_body", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="原始请求体（JSON 格式）"),
    sa.Column("client_ip", sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="客户端 IP 地址"),
    sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True, comment="客户端 User-Agent"),
    sa.Column("request_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="请求 ID（用于链路追踪）"),
    sa.Column("correlation_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="关联 ID（串联整个流程）"),
    sa.Column("response_status", sa.INTEGER(), autoincrement=False, nullable=False, comment="HTTP 响应状态码"),
    sa.Column("response_time_ms", sa.INTEGER(), autoincrement=False, nullable=False, comment="响应时间（毫秒）"),
    sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True, comment="错误消息（如果处理失败）"),
    sa.PrimaryKeyConstraint("id", name=op.f("callback_logs_pkey")),
    schema="wes_biz",
    comment="回调接收日志"
    )
    op.create_index(op.f("ix_callback_logs_request_id"), "callback_logs", ["request_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_callback_logs_device_id"), "callback_logs", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_callback_logs_correlation_id"), "callback_logs", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_callback_logs_callback_type"), "callback_logs", ["callback_type"], unique=False, schema="wes_biz")
    # ### end Alembic commands ###
