"""add_callback_log_table

Revision ID: ab8b14fe397c
Revises: 8f8180e751c3
Create Date: 2026-03-17 16:08:21.761635+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab8b14fe397c"
down_revision: Union[str, Sequence[str], None] = "8f8180e751c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("callback_logs",
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("callback_type", sa.String(), nullable=False),
    sa.Column("device_id", sa.String(length=50), nullable=False),
    sa.Column("request_body", sa.JSON(), nullable=True),
    sa.Column("client_ip", sa.String(length=50), nullable=True),
    sa.Column("user_agent", sa.Text(), nullable=True),
    sa.Column("request_id", sa.String(length=100), nullable=True),
    sa.Column("correlation_id", sa.String(length=100), nullable=True),
    sa.Column("response_status", sa.Integer(), nullable=False),
    sa.Column("response_time_ms", sa.Integer(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_biz"
    )
    op.create_index(op.f("ix_wes_biz_callback_logs_callback_type"), "callback_logs", ["callback_type"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_callback_logs_correlation_id"), "callback_logs", ["correlation_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_callback_logs_device_id"), "callback_logs", ["device_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_callback_logs_id"), "callback_logs", ["id"], unique=True, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_callback_logs_request_id"), "callback_logs", ["request_id"], unique=False, schema="wes_biz")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wes_biz_callback_logs_request_id"), table_name="callback_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_callback_logs_id"), table_name="callback_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_callback_logs_device_id"), table_name="callback_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_callback_logs_correlation_id"), table_name="callback_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_callback_logs_callback_type"), table_name="callback_logs", schema="wes_biz")
    op.drop_table("callback_logs", schema="wes_biz")
    # ### end Alembic commands ###
