"""add menus table and role_menu association

Revision ID: 7530da1be3cd
Revises: 2b4dbcc57a0b
Create Date: 2026-02-11 13:08:28.620356+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7530da1be3cd"
down_revision: Union[str, Sequence[str], None] = "2b4dbcc57a0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("menus",
    sa.Column("deleted_by", sa.Integer(), nullable=True, comment="删除人ID"),
    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
    sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False, comment="是否已删除"),
    sa.Column("version", sa.Integer(), server_default="0", nullable=False, comment="版本号"),
    sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间 (UTC)"),
    sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间 (UTC)"),
    sa.Column("created_by", sa.BigInteger(), nullable=True, comment="创建人ID"),
    sa.Column("updated_by", sa.BigInteger(), nullable=True, comment="更新人ID"),
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键 ID"),
    sa.Column("parent_id", sa.Integer(), nullable=True, comment="父节点ID"),
    sa.Column("tree_path", sa.String(), nullable=False, comment="节点路径"),
    sa.Column("level", sa.Integer(), nullable=False, comment="节点层级"),
    sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序号"),
    sa.Column("name", sa.String(length=50), nullable=False),
    sa.Column("title", sa.String(length=50), nullable=False),
    sa.Column("path", sa.String(length=200), nullable=False),
    sa.Column("component", sa.String(length=200), nullable=True),
    sa.Column("icon", sa.String(length=50), nullable=True),
    sa.Column("is_hidden", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="wes_sys"
    )
    op.create_index(op.f("ix_wes_sys_menus_id"), "menus", ["id"], unique=True, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_menus_parent_id"), "menus", ["parent_id"], unique=False, schema="wes_sys")
    op.create_index(op.f("ix_wes_sys_menus_tree_path"), "menus", ["tree_path"], unique=False, schema="wes_sys")
    op.create_index("ux_menus_name_deleted", "menus", ["name"], unique=True, schema="wes_sys", postgresql_where="NOT is_deleted")
    op.create_table("role_menus",
    sa.Column("role_id", sa.BigInteger(), nullable=False),
    sa.Column("menu_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["menu_id"], ["wes_sys.menus.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["role_id"], ["wes_sys.roles.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("role_id", "menu_id"),
    schema="wes_sys",
    comment="角色-菜单关联表"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_menus", schema="wes_sys")
    op.drop_index("ux_menus_name_deleted", table_name="menus", schema="wes_sys", postgresql_where="NOT is_deleted")
    op.drop_index(op.f("ix_wes_sys_menus_tree_path"), table_name="menus", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_menus_parent_id"), table_name="menus", schema="wes_sys")
    op.drop_index(op.f("ix_wes_sys_menus_id"), table_name="menus", schema="wes_sys")
    op.drop_table("menus", schema="wes_sys")
    # ### end Alembic commands ###
