"""add session_id and workline_id to device commands and event logs

Revision ID: 4884d68cbe09
Revises: be330a8cda0a
Create Date: 2026-03-17 09:19:04.830061+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4884d68cbe09"
down_revision: Union[str, Sequence[str], None] = "be330a8cda0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 device_commands 的新字段
    op.add_column("device_commands", sa.Column("session_id", sa.String(length=100), nullable=True), schema="wes_biz")
    op.add_column("device_commands", sa.Column("workline_id", sa.Integer(), nullable=True), schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_session_id"), "device_commands", ["session_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_workline_id"), "device_commands", ["workline_id"], unique=False, schema="wes_biz")
    op.create_foreign_key(None, "device_commands", "work_lines", ["workline_id"], ["id"], source_schema="wes_biz", referent_schema="wes_biz")

    # 添加 device_event_logs 的新字段
    op.add_column("device_event_logs", sa.Column("session_id", sa.String(length=100), nullable=True), schema="wes_biz")
    op.add_column("device_event_logs", sa.Column("workline_id", sa.Integer(), nullable=True), schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_session_id"), "device_event_logs", ["session_id"], unique=False, schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_workline_id"), "device_event_logs", ["workline_id"], unique=False, schema="wes_biz")
    op.create_foreign_key(None, "device_event_logs", "work_lines", ["workline_id"], ["id"], source_schema="wes_biz", referent_schema="wes_biz")

    # 注释：audit_logs.status 的类型变更已存在，无需重复添加
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 device_event_logs 的约束和字段
    op.drop_constraint(None, "device_event_logs", schema="wes_biz", type_="foreignkey")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_workline_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_session_id"), table_name="device_event_logs", schema="wes_biz")
    op.drop_column("device_event_logs", "workline_id", schema="wes_biz")
    op.drop_column("device_event_logs", "session_id", schema="wes_biz")

    # 删除 device_commands 的约束和字段
    op.drop_constraint(None, "device_commands", schema="wes_biz", type_="foreignkey")
    op.drop_index(op.f("ix_wes_biz_device_commands_workline_id"), table_name="device_commands", schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_session_id"), table_name="device_commands", schema="wes_biz")
    op.drop_column("device_commands", "workline_id", schema="wes_biz")
    op.drop_column("device_commands", "session_id", schema="wes_biz")
    # ### end Alembic commands ###
