"""create callback_logs table

Revision ID: 918aa7b0929d
Revises: 71fdc7253cde
Create Date: 2026-03-04 14:54:49.469311+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "918aa7b0929d"
down_revision: Union[str, Sequence[str], None] = "71fdc7253cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("device_commands", "task_type",
               existing_type=postgresql.ENUM("PICK", "PUT", "SCAN", "ROTATE", "PROCESS", "PICK_AND_PLACE", name="tasktype", schema="wes_biz"),
               type_=sa.Enum("PICK", "PUT", "SCAN", "ROTATE", "PROCESS", "PICK_AND_PLACE", name="tasktype"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "status",
               existing_type=postgresql.ENUM("PENDING", "SENT", "ACK_RECEIVED", "COMPLETED", "FAILED", "TIMEOUT", "CANCELLED", name="commandstatus", schema="wes_biz"),
               server_default=None,
               type_=sa.Enum("PENDING", "SENT", "ACK_RECEIVED", "COMPLETED", "FAILED", "TIMEOUT", "CANCELLED", name="commandstatus"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "result",
               existing_type=postgresql.ENUM("SUCCESS", "FAILED", name="commandresult", schema="wes_biz"),
               type_=sa.Enum("SUCCESS", "FAILED", name="commandresult"),
               existing_nullable=True,
               schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_commands_device_id"), "device_commands", ["device_id"], unique=False, schema="wes_biz")
    op.alter_column("device_event_logs", "event_type",
               existing_type=postgresql.ENUM("ESTOP_PRESSED", "DEVICE_ONLINE", "DEVICE_OFFLINE", "DEVICE_ERROR", "MATERIAL_ARRIVED", "SCAN_COMPLETED", "PICK_COMPLETED", "PUT_COMPLETED", "PROCESS_COMPLETED", name="eventtype", schema="wes_biz"),
               type_=sa.Enum("ESTOP_PRESSED", "DEVICE_ONLINE", "DEVICE_OFFLINE", "DEVICE_ERROR", "MATERIAL_ARRIVED", "SCAN_COMPLETED", "PICK_COMPLETED", "PUT_COMPLETED", "PROCESS_COMPLETED", name="eventtype"),
               existing_nullable=False,
               schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_device_event_logs_device_id"), "device_event_logs", ["device_id"], unique=False, schema="wes_biz")
    op.alter_column("devices", "protocol",
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "timeout",
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "device_status",
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "max_concurrent_tasks",
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "idempotency_ttl",
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("api_applications", "app_type",
               existing_type=postgresql.ENUM("ECS", "RCS", "WMS", "ThirdParty", name="apptype", schema="wes_sys"),
               type_=sa.Enum("ECS", "RCS", "WMS", "ThirdParty", name="apptype"),
               existing_nullable=False,
               schema="wes_sys")
    op.alter_column("api_applications", "validity_period",
               existing_type=postgresql.ENUM("ONE_DAY", "ONE_WEEK", "ONE_MONTH", "SIX_MONTHS", "ONE_YEAR", "NEVER", name="validityperiod", schema="wes_sys"),
               type_=sa.Enum("ONE_DAY", "ONE_WEEK", "ONE_MONTH", "SIX_MONTHS", "ONE_YEAR", "NEVER", name="validityperiod"),
               existing_nullable=False,
               schema="wes_sys")
    op.alter_column("api_applications", "status",
               existing_type=postgresql.ENUM("ACTIVE", "REVOKED", "EXPIRED", name="appstatus", schema="wes_sys"),
               type_=sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="appstatus"),
               existing_nullable=False,
               schema="wes_sys")
    op.alter_column("audit_logs", "status",
               existing_type=postgresql.ENUM("FAIL", "SUCCESS", name="operastatus", schema="wes_sys"),
               type_=sa.Enum("FAIL", "SUCCESS", name="operastatus"),
               existing_nullable=False,
               schema="wes_sys")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("audit_logs", "status",
               existing_type=sa.Enum("FAIL", "SUCCESS", name="operastatus"),
               type_=postgresql.ENUM("FAIL", "SUCCESS", name="operastatus", schema="wes_sys"),
               existing_nullable=False,
               schema="wes_sys")
    op.alter_column("api_applications", "status",
               existing_type=sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="appstatus"),
               type_=postgresql.ENUM("ACTIVE", "REVOKED", "EXPIRED", name="appstatus", schema="wes_sys"),
               existing_nullable=False,
               schema="wes_sys")
    op.alter_column("api_applications", "validity_period",
               existing_type=sa.Enum("ONE_DAY", "ONE_WEEK", "ONE_MONTH", "SIX_MONTHS", "ONE_YEAR", "NEVER", name="validityperiod"),
               type_=postgresql.ENUM("ONE_DAY", "ONE_WEEK", "ONE_MONTH", "SIX_MONTHS", "ONE_YEAR", "NEVER", name="validityperiod", schema="wes_sys"),
               existing_nullable=False,
               schema="wes_sys")
    op.alter_column("api_applications", "app_type",
               existing_type=sa.Enum("ECS", "RCS", "WMS", "ThirdParty", name="apptype"),
               type_=postgresql.ENUM("ECS", "RCS", "WMS", "ThirdParty", name="apptype", schema="wes_sys"),
               existing_nullable=False,
               schema="wes_sys")
    op.alter_column("devices", "idempotency_ttl",
               existing_type=sa.INTEGER(),
               server_default=sa.text("3600"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "max_concurrent_tasks",
               existing_type=sa.INTEGER(),
               server_default=sa.text("1"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "device_status",
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'IDLE'::character varying"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "timeout",
               existing_type=sa.INTEGER(),
               server_default=sa.text("10000"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("devices", "protocol",
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'HTTP'::character varying"),
               existing_nullable=False,
               schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_event_logs_device_id"), table_name="device_event_logs", schema="wes_biz")
    op.alter_column("device_event_logs", "event_type",
               existing_type=sa.Enum("ESTOP_PRESSED", "DEVICE_ONLINE", "DEVICE_OFFLINE", "DEVICE_ERROR", "MATERIAL_ARRIVED", "SCAN_COMPLETED", "PICK_COMPLETED", "PUT_COMPLETED", "PROCESS_COMPLETED", name="eventtype"),
               type_=postgresql.ENUM("ESTOP_PRESSED", "DEVICE_ONLINE", "DEVICE_OFFLINE", "DEVICE_ERROR", "MATERIAL_ARRIVED", "SCAN_COMPLETED", "PICK_COMPLETED", "PUT_COMPLETED", "PROCESS_COMPLETED", name="eventtype", schema="wes_biz"),
               existing_nullable=False,
               schema="wes_biz")
    op.drop_index(op.f("ix_wes_biz_device_commands_device_id"), table_name="device_commands", schema="wes_biz")
    op.alter_column("device_commands", "result",
               existing_type=sa.Enum("SUCCESS", "FAILED", name="commandresult"),
               type_=postgresql.ENUM("SUCCESS", "FAILED", name="commandresult", schema="wes_biz"),
               existing_nullable=True,
               schema="wes_biz")
    op.alter_column("device_commands", "status",
               existing_type=sa.Enum("PENDING", "SENT", "ACK_RECEIVED", "COMPLETED", "FAILED", "TIMEOUT", "CANCELLED", name="commandstatus"),
               server_default=sa.text("'PENDING'::wes_biz.commandstatus"),
               type_=postgresql.ENUM("PENDING", "SENT", "ACK_RECEIVED", "COMPLETED", "FAILED", "TIMEOUT", "CANCELLED", name="commandstatus", schema="wes_biz"),
               existing_nullable=False,
               schema="wes_biz")
    op.alter_column("device_commands", "task_type",
               existing_type=sa.Enum("PICK", "PUT", "SCAN", "ROTATE", "PROCESS", "PICK_AND_PLACE", name="tasktype"),
               type_=postgresql.ENUM("PICK", "PUT", "SCAN", "ROTATE", "PROCESS", "PICK_AND_PLACE", name="tasktype", schema="wes_biz"),
               existing_nullable=False,
               schema="wes_biz")
    # ### end Alembic commands ###
