"""add parent sort index to menus

Revision ID: 6f84ab2bf6e6
Revises: 5d26a11a4cd9
Create Date: 2026-03-31 16:07:13.683842+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f84ab2bf6e6"
down_revision: Union[str, Sequence[str], None] = "5d26a11a4cd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("menus", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    op.drop_index(op.f("idx_tree_parent_sort"), table_name="menus", schema="wes_sys")
    op.create_index("idx_menus_parent_sort", "menus", ["parent_id", "sort_order"], unique=False, schema="wes_sys")
    op.alter_column("permissions", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("permissions", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("false"),
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    op.drop_index("idx_menus_parent_sort", table_name="menus", schema="wes_sys")
    op.create_index(op.f("idx_tree_parent_sort"), "menus", ["parent_id", "sort_order"], unique=False, schema="wes_sys")
    op.alter_column("menus", "has_children",
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("false"),
               existing_comment="是否有子节点",
               existing_nullable=False,
               schema="wes_sys")
    # ### end Alembic commands ###
