"""drop deprecated device fields

Revision ID: ee46b1b4e252
Revises: 60cd0040b702
Create Date: 2026-04-05 20:22:23.024789+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee46b1b4e252"
down_revision: Union[str, Sequence[str], None] = "60cd0040b702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wes_biz_devices_plugin_key"), table_name="devices", schema="wes_biz")
    op.drop_column("devices", "device_type", schema="wes_biz")
    op.drop_column("devices", "contract_version", schema="wes_biz")
    op.drop_column("devices", "capabilities", schema="wes_biz")
    op.drop_column("devices", "plugin_key", schema="wes_biz")
    op.drop_column("devices", "supported_commands", schema="wes_biz")
    op.drop_column("devices", "contract_profile", schema="wes_biz")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("contract_profile", sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("supported_commands", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("plugin_key", sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("capabilities", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("contract_version", sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema="wes_biz")
    op.add_column("devices", sa.Column("device_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema="wes_biz")
    op.create_index(op.f("ix_wes_biz_devices_plugin_key"), "devices", ["plugin_key"], unique=False, schema="wes_biz")
    # ### end Alembic commands ###
