"""extend task type enum for conveyor and output

Revision ID: 60cd0040b702
Revises: 6f84ab2bf6e6
Create Date: 2026-04-05 13:53:12.843607+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60cd0040b702"
down_revision: Union[str, Sequence[str], None] = "6f84ab2bf6e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_menus_parent_sort"), table_name="menus", schema="wes_sys")
    op.create_index("ix_menus_parent_sort", "menus", ["parent_id", "sort_order"], unique=False, schema="wes_sys")
    # ### end Alembic commands ###

    # 手动补充：扩展 TaskType CHECK 约束
    # Alembic 无法自动检测 CHECK 约束变化
    op.execute("""
        ALTER TABLE wes_biz.device_commands
        DROP CONSTRAINT IF EXISTS ck_device_commands_tasktype
    """)
    op.execute("""
        ALTER TABLE wes_biz.device_commands
        ADD CONSTRAINT ck_device_commands_tasktype
        CHECK (task_type IN (
            'PICK', 'PUT', 'SCAN', 'ROTATE', 'PROCESS',
            'PICK_AND_PLACE', 'PICK_AND_PUT',
            'MOVE_FORWARD', 'MOVE_BACKWARD', 'STOP',
            'OUTPUT', 'PICK_NG'
        ))
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # 回滚 CHECK 约束
    op.execute("""
        ALTER TABLE wes_biz.device_commands
        DROP CONSTRAINT IF EXISTS ck_device_commands_tasktype
    """)
    op.execute("""
        ALTER TABLE wes_biz.device_commands
        ADD CONSTRAINT ck_device_commands_tasktype
        CHECK (task_type IN (
            'PICK', 'PUT', 'SCAN', 'ROTATE', 'PROCESS', 'PICK_AND_PLACE'
        ))
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_menus_parent_sort", table_name="menus", schema="wes_sys")
    op.create_index(op.f("idx_menus_parent_sort"), "menus", ["parent_id", "sort_order"], unique=False, schema="wes_sys")
    # ### end Alembic commands ###
