"""add has_children field to tree mixin

Revision ID: 5d26a11a4cd9
Revises: b9e1c2d3f4a5
Create Date: 2026-03-31 16:00:50.735894+08:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d26a11a4cd9"
down_revision: Union[str, Sequence[str], None] = "b9e1c2d3f4a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # menus 表
    op.add_column(
        "menus",
        sa.Column("has_children", sa.Boolean(), nullable=False, server_default="false", comment="是否有子节点"),
        schema="wes_sys",
    )

    # permissions 表
    op.add_column(
        "permissions",
        sa.Column("has_children", sa.Boolean(), nullable=False, server_default="false", comment="是否有子节点"),
        schema="wes_sys",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # permissions 表
    op.drop_column("permissions", "has_children", schema="wes_sys")

    # menus 表
    op.drop_column("menus", "has_children", schema="wes_sys")
    # ### end Alembic commands ###
