#!/bin/bash
# 生成 Alembic 迁移并自动处理 ENUM 类型
# 用法: ./scripts/generate_migration.sh "migration message"

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if [ -z "$1" ]; then
    echo -e "${RED}错误: 缺少迁移消息${NC}"
    echo "用法: $0 <migration_message>"
    echo "示例: $0 \"add user avatar field\""
    exit 1
fi

echo -e "${GREEN}正在生成迁移: $1${NC}"
alembic revision --autogenerate -m "$1"

# 获取最新的迁移文件
LATEST_MIGRATION=$(ls -t alembic/versions/*.py | head -1)
echo -e "${GREEN}生成的迁移文件: $LATEST_MIGRATION${NC}"

# 检查是否包含 ENUM 类型
if grep -q "sa.Enum.*name=" "$LATEST_MIGRATION"; then
    echo ""
    echo -e "${YELLOW}⚠️  检测到 ENUM 类型！${NC}"
    echo "正在自动添加 DROP TYPE IF EXISTS 语句..."

    # 提取所有 ENUM 类型名称（兼容 macOS 的方式）
    ENUM_NAMES=$(python3 -c "
import re

with open('$LATEST_MIGRATION', 'r') as f:
    content = f.read()

pattern = r'sa\.Enum\([^)]*name=[\"' + \"'\" + r']([^\"' + \"'\" + r']+)[\"' + \"'\" + r']'
matches = re.findall(pattern, content)
for name in sorted(set(matches)):
    print(name)
")

    echo -e "${YELLOW}发现的 ENUM 类型: $ENUM_NAMES${NC}"

    # 备份原文件
    cp "$LATEST_MIGRATION" "$LATEST_MIGRATION.bak"

    # 为每个 ENUM 类型添加 DROP TYPE 语句
    for ENUM_NAME in $ENUM_NAMES; do
        # 检查 upgrade() 函数中是否已经有 DROP TYPE 语句
        if ! grep -q "DROP TYPE IF EXISTS $ENUM_NAME" "$LATEST_MIGRATION"; then
            # 在 upgrade() 函数的注释后添加 DROP TYPE
            # 使用 Python 来精确插入，避免 sed 的复杂性
            python3 << EOF
import re

with open("$LATEST_MIGRATION", "r") as f:
    content = f.read()

# 在 upgrade() 函数的 "# ### commands auto generated" 后添加
pattern = r'(def upgrade\(\) -> None:.*?# ### commands auto generated by Alembic.*?\n)'
replacement = r'\1    # 删除已存在的 ENUM 类型（如果存在）\n    op.execute("DROP TYPE IF EXISTS $ENUM_NAME CASCADE")\n\n'
content = re.sub(pattern, replacement, content, flags=re.DOTALL)

# 在 downgrade() 函数的 "# ### end Alembic commands ###" 前添加
pattern = r'(def downgrade\(\) -> None:.*?)(    # ### end Alembic commands ###)'
replacement = r'\1    # 删除 ENUM 类型\n    op.execute("DROP TYPE IF EXISTS $ENUM_NAME CASCADE")\n    \2'
content = re.sub(pattern, replacement, content, flags=re.DOTALL)

with open("$LATEST_MIGRATION", "w") as f:
    f.write(content)
EOF
            echo -e "${GREEN}✓ 已为 $ENUM_NAME 添加 DROP TYPE 语句${NC}"
        else
            echo -e "${GREEN}✓ $ENUM_NAME 的 DROP TYPE 语句已存在${NC}"
        fi
    done

    echo ""
    echo -e "${GREEN}✓ ENUM 类型处理完成${NC}"
    echo -e "${YELLOW}请检查迁移文件以确认修改正确: $LATEST_MIGRATION${NC}"
else
    echo -e "${GREEN}✓ 未检测到 ENUM 类型，无需额外处理${NC}"
fi

echo ""
echo -e "${GREEN}迁移生成完成！${NC}"
echo ""
echo "下一步:"
echo "  1. 检查迁移文件: $LATEST_MIGRATION"
echo "  2. 运行迁移: ./scripts/migrate.sh upgrade"
