"""SMT 分拣入库插件 P0 合同常量。"""

from src.app.runtime.capabilities.material_flow.contracts.ng_reason import NgReasonDefinition, NgReasonSource

SORTING_CONTEXT_SCHEMA_VERSION = 1

ROLE_SORTING_SOURCE_ARM = "SORTING_SOURCE_ARM"
ROLE_SORTING_TARGET_ARM = "SORTING_TARGET_ARM"
ROLE_SORTING_SCAN_PLATFORM = "SORTING_SCAN_PLATFORM"
ROLE_SORTING_WORKSTATION = "SORTING_WORKSTATION"

SMT_SOURCE_PICK_WAIT_CONTEXT_STATE = "WAITING_SOURCE_PICK"
PHASE_WAITING_SCAN = "WAITING_SCAN"
PHASE_WAITING_TARGET_PLACE = "WAITING_TARGET_PLACE"
PHASE_WAITING_TARGET_BIN_SWITCH = "WAITING_TARGET_BIN_SWITCH"
PHASE_WAITING_NG_PLACE = "WAITING_NG_PLACE"

COMMAND_SOURCE_PICK = "SORTING_SOURCE_PICK"
COMMAND_TARGET_PLACE = "SORTING_TARGET_PLACE"
COMMAND_NG_PLACE = "SORTING_NG_PLACE"

EVENT_SOURCE_PICK_REQUESTED = "SORTING_SOURCE_PICK_REQUESTED"
EVENT_WORKING_BIN_SCAN = "WORKING_BIN_SCAN"

NG_REASON_LOCAL_SORTING_NG = "LOCAL_SORTING_NG"
NG_REASON_MATERIAL_CONFLICT = "NG_MATERIAL_CONFLICT"


def list_smt_sorting_inbound_ng_reasons() -> tuple[NgReasonDefinition, ...]:
    """从 generated Definition 身份生成 SMT Hold 的稳定解释。"""

    # 延迟导入避免 Definition 注册 ng resolver 时形成模块导入环。
    from src.app.runtime.workline_plugins.smt_sorting_inbound.definition import DEFINITION

    return (
        NgReasonDefinition(
            canonical_code=NG_REASON_LOCAL_SORTING_NG,
            label="本地分拣 NG",
            source=NgReasonSource.PLUGIN,
            plugin_key=DEFINITION.plugin_key,
            contract_version=DEFINITION.contract_version,
            maps_from=(NG_REASON_LOCAL_SORTING_NG,),
        ),
    )


__all__ = [
    "COMMAND_NG_PLACE",
    "COMMAND_SOURCE_PICK",
    "COMMAND_TARGET_PLACE",
    "EVENT_SOURCE_PICK_REQUESTED",
    "EVENT_WORKING_BIN_SCAN",
    "NG_REASON_LOCAL_SORTING_NG",
    "NG_REASON_MATERIAL_CONFLICT",
    "PHASE_WAITING_NG_PLACE",
    "PHASE_WAITING_SCAN",
    "PHASE_WAITING_TARGET_BIN_SWITCH",
    "PHASE_WAITING_TARGET_PLACE",
    "ROLE_SORTING_SCAN_PLATFORM",
    "ROLE_SORTING_SOURCE_ARM",
    "ROLE_SORTING_TARGET_ARM",
    "ROLE_SORTING_WORKSTATION",
    "SMT_SOURCE_PICK_WAIT_CONTEXT_STATE",
    "SORTING_CONTEXT_SCHEMA_VERSION",
    "list_smt_sorting_inbound_ng_reasons",
]
