"""共享工作位用途枚举，不依赖 ORM 模型注册。"""

from enum import Enum


class WorklineRackPositionRole(str, Enum):
    """工作线停靠位角色。"""

    SMT_CLASSIFIER_SINGLE_RACK_WORK = "SMT_CLASSIFIER_SINGLE_RACK_WORK"
    SMT_RACK_EXCHANGE_AREA = "SMT_RACK_EXCHANGE_AREA"
    SMT_SORTER_QUEUE = "SMT_SORTER_QUEUE"
    SMT_SORTER_STATION = "SMT_SORTER_STATION"
    SMT_RETURN_RACK_POSITION = "SMT_RETURN_RACK_POSITION"
    SMT_TRANSFER_RACK_POSITION = "SMT_TRANSFER_RACK_POSITION"
    SMT_EMPTY_RACK_AREA = "SMT_EMPTY_RACK_AREA"
