from src.app.runtime.system_capabilities.wms.effect_runtime import build_wms_effect_capability_definition
from src.app.wms_integration.ports.fulfillment_operations import MOVE_BINS_TO_CONVEYOR_ENTRY

DEFINITION = build_wms_effect_capability_definition(MOVE_BINS_TO_CONVEYOR_ENTRY)
